version: 1.3.1
main: de.marcely.bedwarsaddon.kits.BWKitAddon
name: MBedwarsKits

authors:
  - Marcely1199
  - Max_Wainer

description: This is an add-on for the plugin Marcelys Bedwars
website: https://marcely.de

api-version: 1.13
depend: [MBedwars]
softdepend:
  - TokenManager
  - TokenEnchant
  - Vault