#######################
# MBedWars Kits
# Version: %{plugin.version}
#######################

version: %{plugin.version}
main: de.marcely.bedwarsaddon.kits.BWKitAddon
name: MBedWarsKits

authors:
  - Marcely1199
  - Max_Wainer

description: This is an add-on for the plugin Marcelys Bedwars
website: https://marcely.de

api-version: 1.13
depend: [MBedwars]
softdepend:
  - TokenManager
  - TokenEnchant
  - Vault
loadbefore:
  - MBedwars

commands: # It's for testing!
  kits: # It's for testing!